# Site metadata
docs_dir: 'RPG Documentation'
site_name: My Legacy App Documentation
site_description: Documentation for the legacy application
site_author: Your Team Name
site_url: https://<your-domain>.github.io/<repository>  # Update for your hosting URL

# Repository information (optional, for GitHub Pages or similar)
repo_name: your-username/your-repo
repo_url: https://github.com/your-username/your-repo

# Theme configuration
theme:
  name: material  # Material for MkDocs for a modern, responsive design
  palette:
    scheme: default  # Auto-switch between light and dark mode
    primary: indigo  # Customize primary color
    accent: amber    # Customize accent color
  features:
    - content.code.copy  # Enable copy button for code blocks
    - content.tabs       # Enable tabbed content
    - navigation.expand  # Expand navigation for nested folders
    - navigation.sections  # Group pages into sections
    - search.suggest      # Search suggestions
    - search.highlight   # Highlight search terms

# Plugins
plugins:
  - search              # Built-in search plugin
  - awesome-pages       # Auto-generate TOC from nested folder structure

# Markdown extensions for enhanced formatting
markdown_extensions:
  - admonition          # Support for callouts (notes, warnings, etc.)
  - pymdownx.details    # Collapsible sections
  - pymdownx.superfences  # Advanced code block formatting
  - pymdownx.highlight: # Syntax highlighting for code
      linenums: true    # Add line numbers to code blocks
  - toc:                # In-page table of contents
      permalink: true   # Add anchor links to headings
  - pymdownx.emoji:     # Emoji support
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed     # Support for tabbed content
  - attr_list           # Allow custom attributes in Markdown
  - md_in_html          # Allow HTML in Markdown

# Optional: Custom navigation (if you want to override awesome-pages for specific sections)
nav:
  - Home: index.md
  - User Guide: user-guide/  # Folder-based navigation, auto-populated by awesome-pages
  - API: api/
  - Troubleshooting: troubleshooting/

# Optional: Extra settings for advanced features
extra:
  social:  # Add links to social or repo pages
    - icon: fontawesome/brands/github
      link: https://github.com/your-username/your-repo
  generator: false  # Hide "Made with MkDocs" footer